version: "3"

networks:
  DMZ1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.50.0/24
  DMZ2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.75.0/24

services:
  server1:
    build:
      context: server
    hostname: server1
    networks:
      DMZ1:
        ipv4_address: 10.0.50.10
      DMZ2:
        ipv4_address: 192.168.75.10
  server2:
    build:
      context: server
    hostname: server2
    networks:
      DMZ1:
        ipv4_address: 10.0.50.20
      DMZ2:
        ipv4_address: 192.168.75.20
  loadbalancer:
    build:
      context: loadbalancer
    hostname: loadbalancer
    networks:
      DMZ1:
        ipv4_address: 10.0.50.5
  mysql:
    image: mariadb:10.9
    container_name: bdd-ctn
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password-root
      MYSQL_DATABASE: bdd-maria
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "40001:3306"
